from pathlib import Path

p=Path('index.html')
s=p.read_text(encoding='utf-8')
marker='MOBILE-HOME-3D-NEAT-20260819'
if marker in s:
    print('already patched')
    raise SystemExit(0)

css='''\n<style id="MOBILE-HOME-3D-NEAT-20260819">\n@media(max-width:850px){\n  /* Titel en intro weer boven de kaart */\n  #home .home-head{order:1!important;padding:16px 18px 10px!important}\n  #home .home-mapcol{order:2!important;padding:0 10px 0!important}\n  #home .home-left{order:3!important}\n  #home .home-right{order:4!important}\n  #home .home-head h1{font-size:clamp(29px,9vw,43px)!important;line-height:1.02;margin:6px 0 8px!important}\n  #home .home-head p{margin:0!important;font-size:11px!important;line-height:1.45!important}\n\n  /* Kleine kaartbediening, echt op de kaart */\n  #home .zoom{left:8px!important;bottom:8px!important;display:flex!important;border-radius:5px!important}\n  #home .zoom button{width:30px!important;height:30px!important;font-size:15px!important;line-height:30px!important;border-bottom:0!important;border-right:1px solid var(--line)!important;padding:0!important}\n  #home .zoom button:last-child{border-right:0!important;font-size:14px!important}\n  #home .targetbar{top:8px!important;right:8px!important;padding:3px!important;gap:3px!important}\n  #home .targetbar button{padding:6px 8px!important;font-size:8px!important}\n\n  /* Iets compacter zodat kaart + titel mooi boven de mobiele balk passen */\n  #home .home-mapcol .mapframe{height:46vh!important;min-height:315px!important;max-height:440px!important}\n\n  /* 3D: hele bunker zichtbaar bij eerste load */\n  #three .threed-head{padding:14px 18px 10px!important}\n  #three .threed-head h1{font-size:clamp(30px,9vw,42px)!important;margin:5px 0 8px!important}\n  #three .threed-head p{font-size:11px!important;line-height:1.45!important;margin:0!important}\n  #three .threed-clean-stage .modelwrap{height:48vh!important;min-height:330px!important;max-height:470px!important}\n}\n@media(max-width:430px){\n  #home .home-mapcol .mapframe{height:44vh!important;min-height:300px!important}\n  #three .threed-clean-stage .modelwrap{height:46vh!important;min-height:315px!important}\n}\n</style>\n'''

js='''\n<script id="mobile-map-3d-framing-20260819">\n(function(){\n  function neatMobileMap(){\n    if(!matchMedia('(max-width:850px)').matches) return;\n    if(typeof centerR616!=='function' || !window.mapframe || !window.mapworld) return;\n    /* >=1.65 voorkomt de lege strook links terwijl R616 exact centraal blijft. */\n    requestAnimationFrame(()=>centerR616(1.68));\n  }\n  function neatMobile3D(){\n    if(!matchMedia('(max-width:850px)').matches) return;\n    if(!window.camera3 || !window.controls3 || !window.mesh3 || !mesh3.geometry) return;\n    const g=mesh3.geometry;\n    if(!g.boundingSphere) g.computeBoundingSphere();\n    if(!g.boundingBox) g.computeBoundingBox();\n    const rad=g.boundingSphere.radius;\n    const h=g.boundingBox.max.y-g.boundingBox.min.y;\n    camera3.position.set(rad*2.65,rad*1.38,rad*2.8);\n    controls3.target.set(0,h*.02,0);\n    controls3.update();\n  }\n\n  window.addEventListener('load',()=>setTimeout(neatMobileMap,140));\n  window.addEventListener('resize',()=>setTimeout(()=>{neatMobileMap();neatMobile3D()},80));\n\n  document.addEventListener('click',e=>{\n    const b=e.target.closest('button');\n    if(!b) return;\n    if(b.dataset.s==='home' || /HOME/i.test(b.textContent||'')) setTimeout(neatMobileMap,90);\n    if(b.dataset.s==='three' || /3D BUNKER/i.test(b.textContent||'')) setTimeout(neatMobile3D,350);\n  });\n\n  /* STL wordt asynchroon geladen; wacht tot het model beschikbaar is. */\n  let tries=0;\n  const timer=setInterval(()=>{\n    if(window.mesh3){ neatMobile3D(); clearInterval(timer); }\n    else if(++tries>40) clearInterval(timer);\n  },250);\n})();\n</script>\n'''

if '</head>' not in s or '</body>' not in s:
    raise SystemExit('expected HTML markers missing')
s=s.replace('</head>',css+'\n</head>',1)
s=s.replace('</body>',js+'\n</body>',1)
p.write_text(s,encoding='utf-8')
print('patched')
